apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
schedulerName: custom-scheduler
leaderElection:
  leaderElect: false
  lockObjectName: custom-scheduler
  lockObjectNamespace: kube-system
plugins:
  filter:
    enabled:
      - name: "PodNodeAffinityPlugin"
  preBind:
    enabled:
      - name: "PodNodeAffinityPlugin"
  bind:
    enabled:
      - name: "PodNodeAffinityPlugin"
    disabled:
      - name: "DefaultBinder"
pluginConfig:
  - name: "PodNodeAffinityPlugin"
    args:
      favorite_color: "#326CE5"
      favorite_number: 7
      thanks_to: "thockin"
